### ISSUE TITLE
使用wordpress规则后waf不拦截

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#100]
版本：ngx_waf:v6.1.9
NGINX版本：nginx/1.22.0
NGINX配置：里面 include /etc/nginx/conf.d/rewrite/wordpress.conf;
wordpress规则：
`
 cat wordpress.conf 

location / {

index index.html index.php;

if (-f $request_filename/index.html){

rewrite (.*) $1/index.html break;

}

if (-f $request_filename/index.php){

rewrite (.*) $1/index.php;

}

if (!-f $request_filename){

rewrite (.*) /index.php;

}

}

`
验证命令：curl https://xxxxxx.com/phpmyadmin/dadmin.html
复现过程：加上wordpress规则，使用命令请求，出现不拦截报404，把wordpress规则去掉，出现拦截报403

**Comment by hibobmaster** [comment]
rewrite指令存在兼容性问题
https://docs.addesp.com/ngx_waf/guide/compatibility.html#module-compatibility
