### ISSUE TITLE
Modsec is end-of-life. Alternate way to add OWASP rules?

### ISSUE THREAD

**Issue by binaryfire** [ADD-SP/ngx_waf#101]
Hello!

The Modsec project is EOL: https://www.trustwave.com/en-us/resources/security-resources/software-updates/end-of-sale-and-trustwave-support-for-modsecurity-web-application-firewall/

But the OWASP core rule set will continue to be developed: https://coreruleset.org/

Is there a way we can add OWASP rules (https://github.com/coreruleset/coreruleset/tree/v4.0/dev/rules) directlty to ngx_waf without Modsec?

**Comment by hibobmaster** [comment]
> Trustwave is announcing the End-of-Life (EOL) of our support for ModSecurity effective July 1, 2024. We will then hand over the maintenance of ModSecurity code back to the open-source community.

ModSecurity is maintained by open-source community nowaday.
