### ISSUE TITLE
how to modify or remove the chinese from the captcha page

### ISSUE THREAD

**Issue by Kiscitkahutta** [ADD-SP/ngx_waf#105]
i am trying to findout it in html files in assets folder but didn't found .....please find the attached SS
(url
![Screenshot from 2022-08-22 11-30-01](https://user-images.githubusercontent.com/50287670/185854356-3cefdcb5-dc55-4c89-aa33-beb31f99928f.png)
)

**Comment by ADD-SP** [comment]
https://add-sp.github.io/ngx_waf-docs/advance/directive.html#waf-captcha

Please see this doc.
