### ISSUE TITLE
nginx: [emerg] "waf_cc_deny" directive is not allowed her

### ISSUE THREAD

**Issue by gongwenbin** [ADD-SP/ngx_waf#106]
ngx_waf版本 current
nginx版本：1.20.2
操作系统：centos7.9
现象：
1、将”waf_cc_deny on rate=10000r/m duration=10m zone=waf:cc;
    waf_cache on capacity=50;“
加入到http段里面，会报错”nginx: [emerg] "waf_cc_deny" directive is not allowed here in /app/software/nginx/conf/nginx.conf:34
nginx: configuration file /app/software/nginx/conf/nginx.conf test failed“。
但是如果加入server则正常。

2、access_log  /app/logs/nginx/waf_block.log  waf if=$waf_blocking_log;  加入到http段里面不生效，需要加入到server方可。

**Comment by ADD-SP** [comment]
目前本模块不支持这两种写法。

**Comment by ADD-SP** [comment]
不过第二个现象确实需要加到文档里。
