### ISSUE TITLE
关于宝塔安装

### ISSUE THREAD

**Issue by mclk623** [ADD-SP/ngx_waf#110]
出现./configure: error: the ngx_http_waf_module module requires the modsecurity library.

**Comment by hibobmaster** [comment]
你需要先编译 modsecurity
参考: https://github.com/ADD-SP/ngx_waf/blob/02dc08c419c6e60bbe1232c82d02f88d06fd624e/config#L75-L97

**Comment by mclk623** [comment]
又有新的错误出现了
-o objs/src/stream/ngx_stream_core_module.o \
src/stream/ngx_stream_core_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_log_module.o \
src/stream/ngx_stream_log_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_proxy_module.o \
src/stream/ngx_stream_proxy_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_upstream.o \
src/stream/ngx_stream_upstream.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_upstream_round_robin.o \
src/stream/ngx_stream_upstream_round_robin.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_write_filter_module.o \
src/stream/ngx_stream_write_filter_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_ssl_module.o \
src/stream/ngx_stream_ssl_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_limit_conn_module.o \
src/stream/ngx_stream_limit_conn_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_access_module.o \
src/stream/ngx_stream_access_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_geo_module.o \
src/stream/ngx_stream_geo_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_map_module.o \
src/stream/ngx_stream_map_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_split_clients_module.o \
src/stream/ngx_stream_split_clients_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_return_module.o \
src/stream/ngx_stream_return_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_set_module.o \
src/stream/ngx_stream_set_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_upstream_hash_module.o \
src/stream/ngx_stream_upstream_hash_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_upstream_least_conn_module.o \
src/stream/ngx_stream_upstream_least_conn_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_upstream_random_module.o \
src/stream/ngx_stream_upstream_random_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_upstream_zone_module.o \
src/stream/ngx_stream_upstream_zone_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/stream \
-o objs/src/stream/ngx_stream_ssl_preread_module.o \
src/stream/ngx_stream_ssl_preread_module.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /www/server/nginx/src/ngx_devel_kit/src -I /www/server/nginx/src/ngx_devel_kit/src -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.0/ -I /www/server/nginx/src/ngx_waf/inc -I /www/server/nginx/src/ngx_waf/lib -I /www/server/nginx/src/ngx_waf/lib/uthash/include -I src/stream \
-o objs/addon/src/ndk.o \
/www/server/nginx/src/ngx_devel_kit/src/ndk.c
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /www/server/nginx/src/ngx_devel_kit/src -I /www/server/nginx/src/ngx_devel_kit/src -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.0/ -I /www/server/nginx/src/ngx_waf/inc -I /www/server/nginx/src/ngx_waf/lib -I /www/server/nginx/src/ngx_waf/lib/uthash/include -I src/stream \
-o objs/addon/src/ngx_http_lua_script.o \
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c: In function ‘ngx_http_lua_script_add_copy_code’:
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c:332:18: error: cast between incompatible function types from ‘size_t (*)(ngx_http_lua_script_engine_t *)’ {aka ‘long unsigned int (*)(struct *)’} to ‘void (*)(ngx_http_lua_script_engine_t *)’ {aka ‘void (*)(struct *)’} [-Werror=cast-function-type]
332 | code->code = (ngx_http_lua_script_code_pt)
| ^
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c: In function ‘ngx_http_lua_script_add_capture_code’:
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c:402:18: error: cast between incompatible function types from ‘size_t (*)(ngx_http_lua_script_engine_t *)’ {aka ‘long unsigned int (*)(struct *)’} to ‘void (*)(ngx_http_lua_script_engine_t *)’ {aka ‘void (*)(struct *)’} [-Werror=cast-function-type]
402 | code->code = (ngx_http_lua_script_code_pt)
| ^
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1809: objs/addon/src/ngx_http_lua_script.o] Error 1
make[1]: Leaving directory '/www/server/nginx/src'
make: *** [Makefile:10: build] Error 2
make -f objs/Makefile install
make[1]: Entering directory '/www/server/nginx/src'
cc -c -I/usr/local/include/luajit-2.0/ -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -std=gnu99 -DNDK_SET_VAR -I src/core -I src/event -I src/event/modules -I src/os/unix -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /www/server/nginx/src/lua_nginx_module/src/api -I pcre-8.43 -I /www/server/nginx/src/openssl/.openssl/include -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /www/server/nginx/src/ngx_devel_kit/src -I /www/server/nginx/src/ngx_devel_kit/src -I /www/server/nginx/src/ngx_devel_kit/objs -I objs/addon/ndk -I /usr/local/include/luajit-2.0/ -I /www/server/nginx/src/ngx_waf/inc -I /www/server/nginx/src/ngx_waf/lib -I /www/server/nginx/src/ngx_waf/lib/uthash/include -I src/stream \
-o objs/addon/src/ngx_http_lua_script.o \
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c: In function ‘ngx_http_lua_script_add_copy_code’:
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c:332:18: error: cast between incompatible function types from ‘size_t (*)(ngx_http_lua_script_engine_t *)’ {aka ‘long unsigned int (*)(struct *)’} to ‘void (*)(ngx_http_lua_script_engine_t *)’ {aka ‘void (*)(struct *)’} [-Werror=cast-function-type]
332 | code->code = (ngx_http_lua_script_code_pt)
| ^
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c: In function ‘ngx_http_lua_script_add_capture_code’:
/www/server/nginx/src/lua_nginx_module/src/ngx_http_lua_script.c:402:18: error: cast between incompatible function types from ‘size_t (*)(ngx_http_lua_script_engine_t *)’ {aka ‘long unsigned int (*)(struct *)’} to ‘void (*)(ngx_http_lua_script_engine_t *)’ {aka ‘void (*)(struct *)’} [-Werror=cast-function-type]
402 | code->code = (ngx_http_lua_script_code_pt)
| ^
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1809: objs/addon/src/ngx_http_lua_script.o] Error 1
make[1]: Leaving directory '/www/server/nginx/src'
make: *** [Makefile:13: install] Error 2
