### ISSUE TITLE
黑名单规则

### ISSUE THREAD

**Issue by nathangary** [ADD-SP/ngx_waf#125]
请问黑名单ip规则，部署在k8s集群环境下，使用ingress访问，看起是用集群ip规则匹配的，如何正确获取客户端ip?

**Comment by ADD-SP** [comment]
https://add-sp.github.io/ngx_waf-docs/zh-cn/guide/faq.html#cdn-%E5%AF%B9-ip-%E6%A3%80%E6%9F%A5%E7%9A%84%E5%BD%B1%E5%93%8D
