### ISSUE TITLE
feat: 能否增加一个 Dockerfile ？

### ISSUE THREAD

**Issue by xiagw** [ADD-SP/ngx_waf#22]
现在用容器的比较多，
可否有一个 官方的Dockerfile

**Comment by ADD-SP** [comment]
在分支 `feature-dockerfile` 上，项目根目录已经增加了 `Dockerfile`，您可以试一下看看行不行。如果没有问题麻烦您关闭这个 issue，如果不行也麻烦提供相关的的信息。

**Comment by xiagw** [comment]
提了一个 PR，修改了一下 dockerfile

用docker mult-stage 减小体积，
修改apk 的中国镜像源
整理一下格式

**Comment by ADD-SP** [comment]
我直接搞一个构建好的镜像然后推送到 Docker 仓库上如何？

**Comment by xiagw** [comment]
应该是提供 dockerfile 比较好。
我提交的 PR 里 加参数就用 阿里云中国镜像
docker build -t test/nginx --build-arg=CHANGE_SOURCE=true .

如果直接推送一个 image，不容易被人采用。主要是官方信任问题。

**Comment by ADD-SP** [comment]
> 应该是提供 dockerfile 比较好。
> 我提交的 PR 里 加参数就用 阿里云中国镜像
> docker build -t test/nginx --build-arg=CHANGE_SOURCE=true .
> 
> 如果直接推送一个 image，不容易被人采用。主要是官方信任问题。

这个确实，非官方的 image 我也不敢完全信任。
