### ISSUE TITLE
English README?

### ISSUE THREAD

**Issue by dvershinin** [ADD-SP/ngx_waf#3]

**Comment by ADD-SP** [comment]
Hello, thank you for your help in this project. This module will release v2.0 within one month and close this issue at the same time. If you think it should not be closed, you can reopen it. Of course, if you think this issue has been resolved, you can also close it yourself.

[v2.0.0-beta.1](https://github.com/ADD-SP/ngx_waf/releases/tag/v2.0.0-beta.1)

**Comment by dvershinin** [comment]
Please see #5. 

On another note, I think `README.md` and `CHANGES.md` should be the English version and something like `README-ZH.md` for Chinese version. (just opinionated, to get some traction for the module, because most users would be probably non-Chinese speaking as myself).

**Comment by ADD-SP** [comment]
Please see aa861da

I think what you said makes sense, so I made the following changes:

* Rename `README-EN.md` to `README.md`
* Rename `CHANGES-EN.md` to `CHANGES.md`
* Rename the old `README.md` to `README-ZH.md`
* Rename the old `CHANGES.md` to `CHANGES-ZH.md`

**Comment by ADD-SP** [comment]
Thank you for your interest in the project, I have closed the issue since [v2.0.0](https://github.com/ADD-SP/ngx_waf/releases/tag/v2.0.0) has been released. If you still have problems you can reopen it.
