### ISSUE TITLE
v4.1.0-beta.3 waf_cache_size 缓存大小参数不见了

### ISSUE THREAD

**Issue by hibobmaster** [ADD-SP/ngx_waf#30]
https://add-sp.github.io/ngx_waf/zh-cn/guide/configuration.html
原本参照这里填写过缓存大小为100M
即`waf_cache_size 100m;`
今天编译了新版本后，`nginx -t` 显示
`nginx: [emerg] ngx_waf: Unable to convert [100m] to a positive integer (22: Invalid argument)`
在v4.1.0-beta.2版本无此问题
最后我参照https://add-sp.github.io/ngx_waf/zh-cn/advance/syntax.html#waf-cache-size
去掉了上述参数，改为`waf_cache_size 120 50;`可以正常重载nginx了
大佬是取消了原本的那个参数吗？以后不需要设置缓存大小了对吧

**Comment by ADD-SP** [comment]
我确实在 v4.1.0-beta.3 中改动了配置语法。由于是开发版，故没有在更新日志中通知。

**Comment by ADD-SP** [comment]
这个测试版以后可能还会有大的变动，不兼容的那种。
