### ISSUE TITLE
ngx_slab_free(): outside of pool

### ISSUE THREAD

**Issue by hibobmaster** [ADD-SP/ngx_waf#32]
在nginx的error log里看到这个alert，请问有啥影响吗？
v5.0.0-beta.2

**Comment by ADD-SP** [comment]
一个内存泄露和一个潜在的段错误。已经在 [v5.0.0-beta.3](https://github.com/ADD-SP/ngx_waf/releases/tag/v5.0.0-beta.3) 修复。

**Comment by hibobmaster** [comment]
fixed!
