### ISSUE TITLE
[Feature Request] 能不能增加js校验功能

### ISSUE THREAD

**Issue by hibobmaster** [ADD-SP/ngx_waf#33]
大佬，你好，突然觉得某些时刻js校验很有用，CC拉黑防不过来了(代理池)。
这个时候有个类似cloudflare的5s盾或者类似[verynginx](https://github.com/alexazhou/VeryNginx)的js或cookie校验可能会好点

这个功能实现方便吗？

**Comment by ADD-SP** [comment]
五秒盾得不偿失。

所谓的五秒盾其实就是通检测到符合条件的请求就返回一个静态 HTML 来代替原本的页面。如果请求直接在 WAF 层面被拦截就直接拦截了，返回一个默认的错误页面，如果返回五秒盾则传输一个静态的 HTML 文件（五秒盾页面），没什么本质区别。之所以 Cloudflare 五秒盾有用，因为五秒盾消耗的是 Cloudflare 的资源（比如带宽）。无需消耗源站的资源。而如果在源站启动五秒盾除了对触发 CC 保护的正常用户有用，没有任何用处。

JS 和 Cookie 校验是什么？具体说说？

**Comment by hibobmaster** [comment]
JS校验就是检测访问者支不支持javascript？像某些爬虫或者自动请求程序是不支持javascript的，cloudflare的5S盾就会检测访问者是否支持javascript,不支持的话就会被拦截。
这个图是verynginx文档里写的
![image](https://user-images.githubusercontent.com/32976627/113570741-8bf70c00-9647-11eb-9880-31003f2f99b6.png)

**Comment by ADD-SP** [comment]
首先，实现复杂，不宜集成进入本模块。其次，这种检测会攻守双方会互相升级，徒增维护难度，如有特殊需求可以自行在后端实现。
