### ISSUE TITLE
waf_cc_deny 和   waf_cache capacity错误

### ISSUE THREAD

**Issue by hacksbsb** [ADD-SP/ngx_waf#34]
请问该如何配置下面规制
    waf on;
    waf_rule_path /usr/local/nginx/conf/rules/;
    waf_mode FULL;
    waf_cc_deny rate=1000r/m;
    waf_cache capacity=50;
    使用nginx -t显示一下错误
    nginx: [emerg] unknown directive "waf_cc_deny" in /usr/local/nginx/conf/nginx.conf:95
    nginx: [emerg] unknown directive " waf_cache capacity" in /usr/local/nginx/conf/nginx.conf:95

**Comment by ADD-SP** [comment]
麻烦发一下命令 `nginx -V` 的输出。

**Comment by hacksbsb** [comment]
ngx_waf的版本是git clone下载源码
未使用动态编译安装ngx_waf 采用静态编译
nginx -V 显示如下:
root@VPS:~# nginx -V
nginx version: nginx/1.19.9
built by gcc 8.3.0 (Debian 8.3.0-6) 
built with OpenSSL 1.1.1k  25 Mar 2021 (running with OpenSSL 1.1.1d  10 Sep 2019)
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_v2_hpack_enc --with-http_ssl_module --with-http_gzip_static_module --with-http_gunzip_module --with-zlib=../zlib --with-http_realip_module --with-http_flv_module --with-threads --with-file-aio --with-http_mp4_module --without-http_scgi_module --without-http_uwsgi_module --with-http_degradation_module --with-http_dav_module --with-http_secure_link_module --with-openssl=../openssl --add-module=../ngx_waf

**Comment by ADD-SP** [comment]
可否伤上传出错的配置文件？我看两行报错指向的都是第 95 行，如果是本模块的问题起码应该报错两行。

**Comment by hacksbsb** [comment]
当时是直接复制的上一行没有改.
nginx.conf配置:
server {
    listen 80;
    server_name _;
    index index.html index.htm index.php;
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    waf on;
    waf_rule_path /usr/local/nginx/conf/rules/;
    waf_mode FULL;
    waf_cc_deny rate=1000r/m;
    waf_cache capacity=50;
显示错误:
root@VPS:/usr/local/nginx/conf# nginx -t
nginx: [emerg] unknown directive "waf_cc_deny" in /usr/local/nginx/conf/nginx.conf:95
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
root@VPS:/usr/local/nginx/conf# nginx -t
nginx: [emerg] unknown directive "waf_cache" in /usr/local/nginx/conf/nginx.conf:96
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

**Comment by ADD-SP** [comment]
看起来应该是使用了旧版本的源码，v5.0.0 之前的稳定版是不支持 `waf_cc_deny  和 `waf_cache` 这两个指令的。

## 需要提供的信息

请提供下面三个命令的输出。

```sh
# 需要提供全部的输出
git tag

# 提供前 10 行的输出
git log

# 提供全部的输出
git remote -v
```

## 解决方法

请进入 ngx_waf 的源码目录，依次执行下面的命令，然后重新编译模块检查是否出错。

```sh
# 删除现有的 clone 源
git remote remove origin

# 添加 Github 上的 clone 源
git remote add origin https://github.com/ADD-SP/ngx_waf.git

# 切换到稳定版分支
git checkout master

# 强制更新到最新的稳定版源码
git pull origin master --rebase --force
```

**Comment by hacksbsb** [comment]
感谢支持,问题已解决
