### ISSUE TITLE
拦截日志能单独定义一个文件吗

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#39]
## 建议
* 拦截日志能单独定义一个文件
* 拦截日志可以定义格式，比如时间的格式2021-05-10 13:02:55这样

**Comment by ADD-SP** [comment]
本模块提供有限的自定义格式功能。

[日志 | ngx_waf](https://add-sp.github.io/ngx_waf/zh-cn/advance/log.html)

**Comment by opcache** [comment]
access_log  logs/access.yml  yaml if=$waf_log;
这样使用，还是有非拦截的日志在里面

**Comment by ADD-SP** [comment]
[内置变量 | ngx_waf](https://add-sp.github.io/ngx_waf/zh-cn/advance/variable.html)

可以通过判断内置变量 `waf_blocked` 的值，然后设置一个自定义变量来实现仅记录拦截日志的功能。

```
server {

    map $waf_blocked$test {
        default 0
        true      1
    }
    access_log logs/access.yml yaml if=$test ;
}
```

**Comment by ADD-SP** [comment]
我今天新增一个变量用来解决这个需求吧，到时候我更新在 beta 版里，更新了之后我会在这里回复。

**Comment by opcache** [comment]
好的,thx

**Comment by ADD-SP** [comment]
新增了一个变量，请下载最新的 beta 版本。按照 [日志 | ngx_waf](https://add-sp.github.io/ngx_waf/zh-cn/advance/log.html) 所示进行操作。

**Comment by ADD-SP** [comment]
[v5.3.0](https://github.com/ADD-SP/ngx_waf/releases/tag/v5.3.0) 已经发布，如测试后无问题请关闭本 issue。
