### ISSUE TITLE
建议拦截可以自定义返回

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#40]
## 建议
* 拦截可以自定义返回文本或者HTML代码
* 当前拦截会返回403，可以配置中自定义返回200，或者其他状态码

**Comment by ADD-SP** [comment]
自定义返回的 HTTP 状态码可以做。

返回自定义页面不做，因为有现成的方法。详见 https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page 。

**Comment by ADD-SP** [comment]
新增了一个配置项：`waf_http_status`，请下载最新的 beta 版，按照 [配置语法 | ngx_waf](https://add-sp.github.io/ngx_waf/zh-cn/advance/syntax.html) 的说明进行操作。

**Comment by ADD-SP** [comment]
[v5.3.0](https://github.com/ADD-SP/ngx_waf/releases/tag/v5.3.0) 已经发布，如测试后无问题请关闭本 issue。
