### ISSUE TITLE
nginx如果reload会重新读取规则吗

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#42]
文档里面说
https://add-sp.github.io/ngx_waf/zh-cn/guide/faq.html#post%E6%A3%80%E6%B5%8B%E5%A4%B1%E6%95%88

可以在运行时修改规则么？
不可以，本模块只会在 nginx 启动时读取规则，之后不再读取。

nginx 如果reload ,会重新读取规则吗？如果会文档建议改下

**Comment by ADD-SP** [comment]
文档说的不太准确，本模块会在 nginx 读取配置时读取规则。reload 时 nginx 会重新读取配置，所以本模块也会重新读取规则。

**文档将在近期更新。**
