### ISSUE TITLE
cc防护要一分钟才能防护？

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#43]
CC 防御参数，1000 每分钟请求次数上限，超出上限后封禁对应 ip 60 分钟。
        waf_cc_deny rate=1000r/m duration=60m;
能不能配置10秒 100次请求上限？
或者10秒300次请求上线？
觉得一分钟有点久，或者20秒，30秒？？如何配置？

**Comment by ADD-SP** [comment]
本模块目前仅支持设置每分钟的请求次数上限，不能更加细化。

为什么要把拦截频率如此细化呢？本模块并不是每分钟集中检查一次访问频率，是一旦某次访问超出了限制就自动封禁了。
