### ISSUE TITLE
waf_rule_type文档漏了CC-DNEY

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#44]
文档中说到
https://add-sp.github.io/ngx_waf/zh-cn/advance/variable.html#waf-rule-type

测试验证发现，少了CC防护的waf_rule_type，CC攻击拦截后，日志里面显示CC-DNEY
还有没其他的waf_rule_type ？建议文档补充 CC-DNEY 和其他的

**Comment by ADD-SP** [comment]
文档已更新。
