### ISSUE TITLE
About Anti-XSS | 关于 XSS 保护

### ISSUE THREAD

**Issue by ADD-SP** [ADD-SP/ngx_waf#45]
I would like to use a third party XSS semantic analysis engine for XSS protection, but I can't find one at the moment, please tell me what XSS semantic analysis engines are available.

***

我想使用第三方的 XSS 语义分析引擎来实现 XSS 保护，不过我现在还没有找到，如果您知道的话请告诉我。

**Comment by hibobmaster** [comment]
https://github.com/keven1z/xssing

**Comment by ADD-SP** [comment]
I chose [libinjection](ttps://github.com/libinjection/libinjection).
