### ISSUE TITLE
模块预构建版本

### ISSUE THREAD

**Issue by soulteary** [ADD-SP/ngx_waf#48]
@ADD-SP 你好👋，我看到有用户反馈编译构建失败，所以做了一个简单的，基于官方容器环境和构建参数的预构建版本（目前只有ubuntu/alpine）

后续或许可以将 scratch 中的二进制模块添加到项目的 release 中，以及添加更多不同的版本预构建文件、以及支持更多的系统/平台。

https://github.com/nginx-with-docker/ngx_http_waf_module

希望对项目有帮助。

**Comment by ADD-SP** [comment]
@soulteary  十分感谢您的努力！

我之前就有提供各个 os/arch 的预构建模块的想法，因为交叉编译比较麻烦所以一直没弄。感觉使用 QEMU + Docker 完成交叉编译的工作可行，之后我会尝试通过提 PR 来完善您的项目。

顺便一提，`libsodium` 并不总是静态链接的，所以目前您构建的模块应该是不能用的，除系统中存在 `libsodium` 的动态库。这个问题我也会在后续提的 PR 中修复。链接模式是如何选择的可以看一下下面的代码片段。

https://github.com/ADD-SP/ngx_waf/blob/5655af6e131f8d4886ec900cd754f903419c0f93/config#L128-L133

**Comment by ADD-SP** [comment]
如果有什么想法可以在这里讨论一下。我目前希望可以通过 Github Action 自动完成构建和发布。
