### ISSUE TITLE
IP 黑名单似乎不支持 0.0.0.0/0 ？

### ISSUE THREAD

**Issue by saytesnake** [ADD-SP/ngx_waf#59]
版本为最新的 ngx_waf v7.0.0 Current，Nginx 版本为 1.20.1，预编译的动态模块（sh assets/download.sh 1.20.1 current）

测试环境配置好 Nginx 之后，在 ipv4 写上 0.0.0.0/0，在 white-ipv4 写上本机 IP 如 192.168.1.100，实际效果是黑名单没有生效，其它 IP 的机器都可以访问得到网站。

将某个 IP 如 192.168.1.101 加入到黑名单后，在 192.168.1.101 这台机器上是无法访问到网站的，证明黑名单已生效。

其实就是想知道，是否支持纯白名单模式。

**Comment by ADD-SP** [comment]
感谢您发现了这个 bug，我们开发时确实没有考虑到形如 `w.x.y.z/0` 这样的 IP 地址。修复补丁已经上传到 `current-dev` 分支，您可以下载测试。

如果 bug 被修复请您关闭本 issue，反之请告知。
