### ISSUE TITLE
为何v6.x和v7.x都没了Dockerfile.alpine

### ISSUE THREAD

**Issue by opcache** [ADD-SP/ngx_waf#60]
**有个问题**

v6.x和v7.x还有v8.x里面都是 Dockerfile.musl，怎么和v5.x里面 Dockerfile.alpine 不一样了
使用 Dockerfile.musl 编译的镜像无法启动，里面没nginx
建议v6.x和v7.x还有v8.x和v5.x一样都提供下 Dockerfile.alpine

**Comment by ADD-SP** [comment]
如非特殊情况，不再提供具体操作系统的镜像和构建脚本。现在只提供已经编译好的动态模块。

原因是并不是所有的用户都只安装本模块，可能会安装许多模块，提供已经一个完整的 nginx 不如提供了已经编译好的动态模块来的灵活。

如果你需要在 alpine 中使用本模块可以自己写一个构建脚本。

下面这种方式无需在本地构建模块。

```Dockerfile
FROM nginx:stable-alpine
COPY --from=addsp/ngx_waf-prebuild:ngx-stable-module-current-musl /modules/ngx_http_waf_module.so /path/to/ngx_http_waf_module.so
```

如果你希望在本地构建模块，你可以直接修改现有的 `Dockerfile.musl`，将编译好的动态模块拷贝到一个 nginx 的镜像中即可。也就稍微改改而已。

**Comment by opcache** [comment]
这么说 v6.x和v7.x还有v8.x编译生成ngx_http_waf_module.so，然后nginx的module里面加载上，就可以使用了 ？

**Comment by ADD-SP** [comment]
对，`Docerfile.musl` 生成的模块可以用于 Alpine 的 nginx 镜像。`Dockerfile.glibc` 生成的模块而可以用于 Debian 的 nginx 镜像。

**Comment by opcache** [comment]
> 
> 
> 对，`Docerfile.musl` 生成的模块可以用于 Alpine 的 nginx 镜像。`Dockerfile.glibc` 生成的模块而可以用于 Debian 的 nginx 镜像。

 好的，我试试
