### ISSUE TITLE
在nginx的stream模块使用ngx_waf的问题

### ISSUE THREAD

**Issue by zhulink** [ADD-SP/ngx_waf#63]
在nginx的stream模块能使用ngx_waf吗

**Comment by ADD-SP** [comment]
不能，ngx_waf 的 HTTP 防火墙，仅能工作在 OSI 模型的应用层，不能工作在传输层。

**Comment by zhulink** [comment]
> 不能，ngx_waf 的 HTTP 防火墙，仅能工作在 OSI 模型的应用层，不能工作在传输层。

好的，谢谢
