### ISSUE TITLE
is ngx_waf can possible compatible with openresty?

### ISSUE THREAD

**Issue by mootechcdn** [ADD-SP/ngx_waf#67]
Hi ,

I'm tested on nginx working perfect, 
but in my prod env we are using openresty ,
so is possible compile with openresty ?
thanks

**Comment by ADD-SP** [comment]
Hi,

Theoretically it is fully compatible as nginx is a component of openresty.

We did a simple test on openresty and found no problems.

If you find any problems in using it, please let me know.

Best regards

**Comment by mootechcdn** [comment]
hi sir , thanks a lot
I'm compiled successfully on openresty
