### ISSUE TITLE
Modules ngx_http_waf_module.so error version 1021003 instead of 1020001 in webmin

### ISSUE THREAD

**Issue by NgHuuAn** [ADD-SP/ngx_waf#71]
Hi,

We got this errors when setup nginx with webmin, can you help us check it. 

![image](https://user-images.githubusercontent.com/31845795/137309749-7e517072-5626-429d-8930-dbe2312c643e.png)

nginx: [emerg] module "/usr/share/nginx/modules/ngx_http_waf_module.so" version 1021003 instead of 1020001 in /usr/share/nginx/modules/load_modules.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

Thanks and Regards !

**Comment by ADD-SP** [comment]
How did you install the module? If you compiled from nginx source code, make sure the nginx source code is the same version.
