### ISSUE TITLE
谷歌爬虫误判

### ISSUE THREAD

**Issue by purplegrape** [ADD-SP/ngx_waf#76]
1、环境：
amazon 2
nginx 1.20.2
ngx_http_waf  10.0.1

2、配置
waf_captcha on GoogleBot BingBot BaiduSpider YandexBot ；

3、日志
2021/12/14 11:29:32 [alert] 30774#30774: *13 ngx_waf: [FAKE-BOT][GoogleBot] while logging request, client: 66.249.72.160, server: www.abc.com, request: "GET /xxx/ HTTP/1.1", subrequest: "/index.php", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock", host: "www.abc.com"

4、谷歌爬虫地址表
https://developers.google.com/search/apis/ipranges/googlebot.json

**Comment by ADD-SP** [comment]
并未误判，只是错误地打印了日志，并不影响爬虫的访问。你可以改用 `current-dev` 分支的代码，已经修复了。

**Comment by ADD-SP** [comment]
Fixed on `v10.1.0`.
