### ISSUE TITLE
config时会报出ssl模块不匹配，请问应该怎么解决

### ISSUE THREAD

**Issue by smallhorsegg** [ADD-SP/ngx_waf#77]
objs/addon/src/ngx_stream_lua_args.o \
objs/addon/src/ngx_stream_lua_ssl.o \
objs/addon/src/ngx_stream_lua_balancer.o \
objs/addon/src/ngx_stream_lua_logby.o \
objs/addon/src/ngx_stream_lua_prereadby.o \
objs/addon/src/ngx_stream_lua_semaphore.o \
objs/addon/src/ngx_stream_lua_ssl_certby.o \
objs/addon/src/ngx_stream_lua_log_ringbuf.o \
objs/addon/src/ngx_stream_lua_input_filters.o \
objs/addon/src/ngx_http_waf_module_core.o \
objs/addon/src/ngx_http_waf_module_var.o \
objs/addon/src/ngx_http_waf_module_action.o \
objs/addon/src/ngx_http_waf_module_data.o \
objs/addon/src/ngx_http_waf_module_check.o \
objs/addon/src/ngx_http_waf_module_config.o \
objs/addon/src/ngx_http_waf_module_ip_trie.o \
objs/addon/src/ngx_http_waf_module_lru_cache.o \
objs/addon/src/ngx_http_waf_module_mem_pool.o \
objs/addon/src/ngx_http_waf_module_shm.o \
objs/addon/src/ngx_http_waf_module_under_attack.o \
objs/addon/src/ngx_http_waf_module_captcha.o \
objs/addon/src/ngx_http_waf_module_verify_bot.o \
objs/addon/src/ngx_http_waf_module_modsecurity.o \
objs/addon/src/ngx_http_waf_module_util.o \
objs/addon/cjson/cJSON.o \
objs/ngx_modules.o \
-L/root/rpmbuild/BUILD/openresty-1.19.3.99/build/luajit-root/usr/local/openresty/luajit/lib -L/root/rpmbuild/BUILD/openresty-1.19.3.99/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib -Wl,--require-defined=pcre_version -Wl,-E -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/root/rpmbuild/BUILD/openresty-1.19.3.99/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -L/root/rpmbuild/BUILD/openresty-1.19.3.99/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -L /usr/local/modsecurity/lib -Wl,-rpath,/usr/local/modsecurity/lib:/usr/local/modsecurity/lib -l modsecurity -l curl -L /usr/local/src/libsodium/lib -Wl,-Bstatic -l sodium -Wl,-Bdynamic -lpcre -lssl -lcrypto -ldl -lpthread -lz \
-Wl,-E
/usr/bin/ld: warning: libssl.so.10, needed by //usr/lib64/libssh2.so.1, may conflict with libssl.so.1.1
/usr/bin/ld: objs/src/event/ngx_event_openssl.o: undefined reference to symbol 'SSL_CTX_get_ex_new_index@@libssl.so.10'
//usr/lib64/libssl.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1

**Comment by ADD-SP** [comment]
看起来是因为有两个版本的 libssh 库，大概需要卸载其中一个版本，没处理过这种情况，卸载其中一个版本也可能导致部分软件出错。

你可以参考一下下列链接。

* https://github.com/rauc/rauc/issues/303
* https://stackoverflow.com/questions/55185403/how-do-i-fix-openssl-error-libssl-so-10-needed-by-lib64-libldap-so-may-confli

**Comment by smallhorsegg** [comment]
> 看起来是因为有两个版本的 libssh 库，大概需要卸载其中一个版本，没处理过这种情况，卸载其中一个版本也可能导致部分软件出错。
> 
> 你可以参考一下下列链接。
> 
> * [Error on "make" rauc/rauc#303](https://github.com/rauc/rauc/issues/303)
> * https://stackoverflow.com/questions/55185403/how-do-i-fix-openssl-error-libssl-so-10-needed-by-lib64-libldap-so-may-confli

./configure: error: SSL modules require the OpenSSL library.
You can either do not enable the modules, or install the OpenSSL library
into the system, or build the OpenSSL library statically from the source
with nginx by using --with-openssl=<path> option.

ERROR: failed to run command: sh ./configure --prefix=/usr/local/openresty/nginx \...
错误：/var/tmp/rpm-tmp.TfOIsI (%build) 退出状态不好
请问这个报错应该怎么处理？  我手动configure没问题，但是rpmbuild时没找到相关的ssl库，不过我已经全部安装了openssl的包

**Comment by smallhorsegg** [comment]
openssl-devel-1.0.2k-22.el7_9.x86_64
openresty-openssl111-1.1.1l-1.el7.x86_64
openssl-perl-1.0.2k-22.el7_9.x86_64
openssl-static-1.0.2k-22.el7_9.x86_64
openssl-1.0.2k-22.el7_9.x86_64
openssl-libs-1.0.2k-22.el7_9.x86_64
openresty-openssl111-devel-1.1.1l-1.el7.x86_64
openssl11-libs-1.1.1k-2.el7.x86_64
openssl11-static-1.1.1k-2.el7.x86_64
openssl-pkcs11-0.4.10-1.el7.x86_64
openssl098e-0.9.8e-29.el7.centos.3.x86_64
openssl11-devel-1.1.1k-2.el7.x86_64
openssl11-1.1.1k-2.el7.x86_64

**Comment by ADD-SP** [comment]
很奇怪，不然重启一下机器碰碰运气？

**Comment by smallhorsegg** [comment]
> 很奇怪，不然重启一下机器碰碰运气？

还是不行，或者Yum 安装的openssl不兼容么？

**Comment by ADD-SP** [comment]
> openssl-devel-1.0.2k-22.el7_9.x86_64 openresty-openssl111-1.1.1l-1.el7.x86_64 openssl-perl-1.0.2k-22.el7_9.x86_64 openssl-static-1.0.2k-22.el7_9.x86_64 openssl-1.0.2k-22.el7_9.x86_64 openssl-libs-1.0.2k-22.el7_9.x86_64 openresty-openssl111-devel-1.1.1l-1.el7.x86_64 openssl11-libs-1.1.1k-2.el7.x86_64 openssl11-static-1.1.1k-2.el7.x86_64 openssl-pkcs11-0.4.10-1.el7.x86_64 openssl098e-0.9.8e-29.el7.centos.3.x86_64 openssl11-devel-1.1.1k-2.el7.x86_64 openssl11-1.1.1k-2.el7.x86_64

看起来你安装的 Openssl 版本太多了，只保留一个版本试试。

**Comment by smallhorsegg** [comment]
> > openssl-devel-1.0.2k-22.el7_9.x86_64 openresty-openssl111-1.1.1l-1.el7.x86_64 openssl-perl-1.0.2k-22.el7_9.x86_64 openssl-static-1.0.2k-22.el7_9.x86_64 openssl-1.0.2k-22.el7_9.x86_64 openssl-libs-1.0.2k-22.el7_9.x86_64 openresty-openssl111-devel-1.1.1l-1.el7.x86_64 openssl11-libs-1.1.1k-2.el7.x86_64 openssl11-static-1.1.1k-2.el7.x86_64 openssl-pkcs11-0.4.10-1.el7.x86_64 openssl098e-0.9.8e-29.el7.centos.3.x86_64 openssl11-devel-1.1.1k-2.el7.x86_64 openssl11-1.1.1k-2.el7.x86_64
> 
> 看起来你安装的 Openssl 版本太多了，只保留一个版本试试。

确实如您所说，我这边只保留一个openssl就行了，但最后又有新的问题:
objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_set_cert':
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1268: undefined reference to `sk_num'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1273: undefined reference to `sk_value'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1290: undefined reference to `sk_value'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1288: undefined reference to `sk_num'
objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_ssl_verify_client':
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1440: undefined reference to `sk_new_null'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1447: undefined reference to `sk_value'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1460: undefined reference to `sk_push'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1446: undefined reference to `sk_num'
/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1485: undefined reference to `sk_free'
collect2: error: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9'

**Comment by ADD-SP** [comment]
看起来是少了 Openssl 某个动态库。

**Comment by smallhorsegg** [comment]
> 看起来是少了 Openssl 某个动态库。

会不会跟waf所需要的openssl库不兼容

**Comment by ADD-SP** [comment]
不会

**Comment by ADD-SP** [comment]
把你现在所有的 openssl 有关的包都发一下。

**Comment by ADD-SP** [comment]
> > > openssl-devel-1.0.2k-22.el7_9.x86_64 openresty-openssl111-1.1.1l-1.el7.x86_64 openssl-perl-1.0.2k-22.el7_9.x86_64 openssl-static-1.0.2k-22.el7_9.x86_64 openssl-1.0.2k-22.el7_9.x86_64 openssl-libs-1.0.2k-22.el7_9.x86_64 openresty-openssl111-devel-1.1.1l-1.el7.x86_64 openssl11-libs-1.1.1k-2.el7.x86_64 openssl11-static-1.1.1k-2.el7.x86_64 openssl-pkcs11-0.4.10-1.el7.x86_64 openssl098e-0.9.8e-29.el7.centos.3.x86_64 openssl11-devel-1.1.1k-2.el7.x86_64 openssl11-1.1.1k-2.el7.x86_64
> > 
> > 
> > 看起来你安装的 Openssl 版本太多了，只保留一个版本试试。
> 
> 确实如您所说，我这边只保留一个openssl就行了，但最后又有新的问题: objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_set_cert': /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1268: undefined reference to `sk_num' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1273: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1290: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1288: undefined reference to `sk_num' objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_ssl_verify_client': /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1440: undefined reference to `sk_new_null' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1447: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1460: undefined reference to `sk_push' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1446: undefined reference to `sk_num' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1485: undefined reference to `sk_free' collect2: error: ld returned 1 exit status make[2]: *** [objs/nginx] Error 1 make[2]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9' make[1]: *** [build] Error 2 make[1]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9'

保留一个？应该是保留一个版本。

**Comment by smallhorsegg** [comment]
> 把你现在所有的 openssl 有关的包都发一下。

[root@VM-168-39-centos ~]# rpm -qa|grep openssl
openssl-libs-1.0.2k-22.el7_9.x86_64
openresty-openssl111-1.1.1l-1.el7.x86_64
openssl-devel-1.0.2k-22.el7_9.x86_64
openresty-openssl111-devel-1.1.1l-1.el7.x86_64
openssl-1.0.2k-22.el7_9.x86_64

这是所有跟openssl相关的包

**Comment by smallhorsegg** [comment]
> > > > openssl-devel-1.0.2k-22.el7_9.x86_64 openresty-openssl111-1.1.1l-1.el7.x86_64 openssl-perl-1.0.2k-22.el7_9.x86_64 openssl-static-1.0.2k-22.el7_9.x86_64 openssl-1.0.2k-22.el7_9.x86_64 openssl-libs-1.0.2k-22.el7_9.x86_64 openresty-openssl111-devel-1.1.1l-1.el7.x86_64 openssl11-libs-1.1.1k-2.el7.x86_64 openssl11-static-1.1.1k-2.el7.x86_64 openssl-pkcs11-0.4.10-1.el7.x86_64 openssl098e-0.9.8e-29.el7.centos.3.x86_64 openssl11-devel-1.1.1k-2.el7.x86_64 openssl11-1.1.1k-2.el7.x86_64
> > > 
> > > 
> > > 看起来你安装的 Openssl 版本太多了，只保留一个版本试试。
> > 
> > 
> > 确实如您所说，我这边只保留一个openssl就行了，但最后又有新的问题: objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_set_cert': /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1268: undefined reference to `sk_num' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1273: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1290: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1288: undefined reference to `sk_num' objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_ssl_verify_client': /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1440: undefined reference to `sk_new_null' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1447: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1460: undefined reference to `sk_push' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1446: undefined reference to `sk_num' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1485: undefined reference to `sk_free' collect2: error: ld returned 1 exit status make[2]: *** [objs/nginx] Error 1 make[2]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9' make[1]: *** [build] Error 2 make[1]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9'
> 
> 保留一个？应该是保留一个版本。

口误  保留一个版本

**Comment by smallhorsegg** [comment]
curl -I -o /dev/null --user-agent bench -s -w "%{http_code}\\n" https://example.com/. 

> > > > openssl-devel-1.0.2k-22.el7_9.x86_64 openresty-openssl111-1.1.1l-1.el7.x86_64 openssl-perl-1.0.2k-22.el7_9.x86_64 openssl-static-1.0.2k-22.el7_9.x86_64 openssl-1.0.2k-22.el7_9.x86_64 openssl-libs-1.0.2k-22.el7_9.x86_64 openresty-openssl111-devel-1.1.1l-1.el7.x86_64 openssl11-libs-1.1.1k-2.el7.x86_64 openssl11-static-1.1.1k-2.el7.x86_64 openssl-pkcs11-0.4.10-1.el7.x86_64 openssl098e-0.9.8e-29.el7.centos.3.x86_64 openssl11-devel-1.1.1k-2.el7.x86_64 openssl11-1.1.1k-2.el7.x86_64
> > > 
> > > 
> > > 看起来你安装的 Openssl 版本太多了，只保留一个版本试试。
> > 
> > 
> > 确实如您所说，我这边只保留一个openssl就行了，但最后又有新的问题: objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_set_cert': /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1268: undefined reference to `sk_num' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1273: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1290: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1288: undefined reference to `sk_num' objs/addon/src/ngx_stream_lua_ssl_certby.o: In function `ngx_stream_lua_ffi_ssl_verify_client': /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1440: undefined reference to `sk_new_null' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1447: undefined reference to `sk_value' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1460: undefined reference to `sk_push' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1446: undefined reference to `sk_num' /root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9/../ngx_stream_lua-0.0.10/src/ngx_stream_lua_ssl_certby.c:1485: undefined reference to `sk_free' collect2: error: ld returned 1 exit status make[2]: *** [objs/nginx] Error 1 make[2]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9' make[1]: *** [build] Error 2 make[1]: Leaving directory `/root/rpmbuild/BUILD/openresty-1.19.9.99/build/nginx-1.19.9'
> 
> 保留一个？应该是保留一个版本。

curl -I -o /dev/null --user-agent bench -s -w "%{http_code}\\n" https://example.com/ 
 请问大佬，http返回码是200是怎么回事？  是不是一定要是403才算模块正常？

**Comment by ADD-SP** [comment]
建议跑一遍文档中的自动测试。
