### ISSUE TITLE
white_url白名单日志问题

### ISSUE THREAD

**Issue by purplegrape** [ADD-SP/ngx_waf#79]
amazon linux 2
nginx 1.20.2
ngx_http_waf  10.1.0

static 域名全站 access_log off ;  但waf url白名单中的 /robots.txt 依然打印在日志里。  

2021/12/20 03:26:15 [alert] 14763#14763: *377 ngx_waf: [WHITE-URL][/robots.txt] while logging request, client: 172.31.29.8, server: static.example.com, request: "GET /robots.txt HTTP/1.1", host: "172.31.17.26"

**Comment by ADD-SP** [comment]
access_log 指令并不能控制 ngx_waf 的日志打印，因为 ngx_waf 打印的属于错误日志。
