### ISSUE TITLE
build error in nginx 1.21.5 PCRE2

### ISSUE THREAD

**Issue by ehdud8451** [ADD-SP/ngx_waf#81]
* How to trigger this bug?
in build source
* The name and version of the OS.
Ubuntu 20.04 LTS
* The version or branch of `ngx_waf`.
ngx_waf 10.1.0
* Output of `nginx -V`.
nginx 1.21.5
* Log
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c: In function ‘_change_modsecurity_pcre_callback’:
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c:2412:9: error: ‘pcre_malloc’ undeclared (first use in this function); did you mean ‘realloc’?
 2412 |     if (pcre_malloc != _modsecurity_pcre_malloc) {
      |         ^~~~~~~~~~~
      |         realloc
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c:2412:9: note: each undeclared identifier is reported only once for each function it appears in
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c:2416:38: error: ‘pcre_free’ undeclared (first use in this function); did you mean ‘curl_free’?
 2416 |         _old_modsecurity_pcre_free = pcre_free;
      |                                      ^~~~~~~~~
      |                                      curl_free
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c: In function ‘_recover_modsecurity_pcre_callback’:
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c:2435:9: error: ‘pcre_malloc’ undeclared (first use in this function); did you mean ‘realloc’?
 2435 |         pcre_malloc = _old_modsecurity_pcre_malloc;
      |         ^~~~~~~~~~~
      |         realloc
/usr/local/src/ngx_waf/src/ngx_http_waf_module_config.c:2436:9: error: ‘pcre_free’ undeclared (first use in this function); did you mean ‘curl_free’?
 2436 |         pcre_free = _old_modsecurity_pcre_free;
      |         ^~~~~~~~~
      |         curl_free
make[1]: *** [objs/Makefile:1789: objs/addon/src/ngx_http_waf_module_config.o] Error 1

--

I think error occurred when nginx 1.21.5 use pcre2.
https://github.com/nginx/nginx/commit/c6fec0b027569a4e0b1d8aaee7dea0f2e4d6052b#diff-bcb19bf17af086d8a980b0f90c7e3e1f9cc4bdd0881fa3c95b2ca16fe6c11438

what can i do?

**Comment by ADD-SP** [comment]
Try the branch `current-dev`, it might work.

**Comment by ADD-SP** [comment]
Solved?

**Comment by ehdud8451** [comment]
I'm sorry for the late response.
An error was found in connection with this, but I'll check if this is an error related to ngx_waf and reply again.

**Comment by ehdud8451** [comment]
-ldl -lpthread -lcrypt -lm -Wl,-rpath,/usr/local/modsecurity/lib -l modsecurity -l curl -l sodium -lpcre2-8 /usr/local/src/openssl/.openssl/lib/libssl.a /usr/local/src/openssl/.openssl/lib/libcrypto.a -ldl -lpthread -lz \
-Wl,-E
/usr/bin/ld: objs/addon/src/ngx_http_waf_module_config.o: undefined reference to symbol 'pcre_malloc'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpcre.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:320: objs/nginx] Error 1
make[1]: Leaving directory '/usr/local/src/nginx/nginx-1.21.5'
make: *** [Makefile:10: build] Error 2


I'm a beginner. I can't check why this error appears. What can I do?

**Comment by ADD-SP** [comment]
It looks like there are some compatibility issues with pcre2, I'll let you know when I fix it.

**Comment by ADD-SP** [comment]
Retry the branch `current-dev` :) .

**Comment by ADD-SP** [comment]
@ehdud8451 Solved?

**Comment by ADD-SP** [comment]
`v10.1.1` can now be compiled with PCRE2.
