### ISSUE TITLE
开启 ModSecurity后性能影响的问题有什么好方案解决吗？ 除了这里的静态配置https://docs.addesp.com/ngx_waf/zh-cn/practice/enable-modsecurity.html

### ISSUE THREAD

**Issue by smallhorsegg** [ADD-SP/ngx_waf#82]

**Comment by ADD-SP** [comment]
没有，因为 ModSecurity 的规则十分复杂，又涉及到硬盘和网络 I/O，缓存也不适用。

**Comment by ADD-SP** [comment]
可能最好的办法就是优化 ModSecurity 引擎本身。

**Comment by ADD-SP** [comment]
详情可以看看 https://github.com/ADD-SP/ngx_waf/issues/73#issuecomment-990742022 。

**Comment by smallhorsegg** [comment]
> 没有，因为 ModSecurity 的规则十分复杂，又涉及到硬盘和网络 I/O，缓存也不适用。

开启后发现cpu使用率飙升，而且磁盘io也非常高

**Comment by ADD-SP** [comment]
硬盘 I/O 很高可以通过关闭审计日志解决。CPU 高很头疼，之前已经尝试过许多优化方法了，没有发现适用的。

**Comment by smallhorsegg** [comment]
> 

okok  thx
