### ISSUE TITLE
GeoIP

### ISSUE THREAD

**Issue by sajjadjafaribojd** [ADD-SP/ngx_waf#91]
Hello.
Is there GeoIP capability in this module?
I read the documentation. But nothing was found about GeoIP.

**Comment by ADD-SP** [comment]
This module is compatible with https://github.com/leev/ngx_http_geoip2_module .

**Comment by sajjadjafaribojd** [comment]
Excellent. I used this module independently
Are there any tips for integrating this module with WAF?
I did not see the GeoIP usage guide in the documentation.

**Comment by ADD-SP** [comment]
@sajjadjafaribojd 
This module can be used with https://github.com/leev/ngx_http_geoip2_module . and no conflicts have been found.
