### ISSUE TITLE
waf_rule_path in http context works improperly

### ISSUE THREAD

**Issue by ononoki1** [ADD-SP/ngx_waf#94]
## Problem
The following config will not work:
```txt
http {
  waf_rule_path /path/to/rule/;
  server {
    waf on;
  }
}
```
While the following one works:
```txt
http {
  server {
    waf on;
    waf_rule_path /path/to/rule/;
  }
}
```
And this one also works:
```txt
http {
  waf on;
  waf_rule_path /path/to/rule/;
  server {
  }
}
```
Technically, NGINX's current context's config should inherit its parent's one, which is not the case in this particular circumstance. I think this should be a bug instead of a feature.

**Comment by ononoki1** [comment]
The ngx_waf version is latest current branch.

**Comment by ononoki1** [comment]
What can I do to help investigate this issue?

**Comment by ADD-SP** [comment]
https://github.com/ADD-SP/ngx_waf/blob/107cca9dec00edf97a9cd9f18cca465284e044bc/src/ngx_http_waf_module_config.c#L1761-L1774

https://github.com/ADD-SP/ngx_waf/blob/107cca9dec00edf97a9cd9f18cca465284e044bc/src/ngx_http_waf_module_config.c#L187-L203

**Comment by ononoki1** [comment]
Since it's not a security bug and has a workaround, I just close it. You can reopen it when having time to solve.
