### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by skydeadpeng** [ADD-SP/ngx_waf#95]
centos7 tengine-2.2.1  make 的时候报错。          
-lpthread -ldl -lcrypt -lpcre -lssl -lcrypto -ldl -lz
objs/addon/src/ngx_http_waf_module_core.o：在函数‘ngx_http_waf_init_process’中：
/usr/local/src/ngx_waf/src/ngx_http_waf_module_core.c:112：对‘randombytes_stir’未定义的引用
objs/addon/src/ngx_http_waf_module_util.o：在函数‘ngx_http_waf_rand_str’中：
/usr/local/src/ngx_waf/src/ngx_http_waf_module_util.c:485：对‘randombytes_uniform’未定义的引用
objs/addon/src/ngx_http_waf_module_util.o：在函数‘ngx_http_waf_sha256’中：
/usr/local/src/ngx_waf/src/ngx_http_waf_module_util.c:507：对‘crypto_hash_sha256’未定义的引用
/usr/local/src/ngx_waf/src/ngx_http_waf_module_util.c:508：对‘sodium_bin2hex’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [objs/nginx] 错误 1
make[1]: 离开目录“/usr/local/src/tengine-2.2.1”

**Comment by ADD-SP** [comment]
Solved
