### ISSUE TITLE
LTS 6.1.8 fails to compile against NGINX 1.23.0

### ISSUE THREAD

**Issue by dvershinin** [ADD-SP/ngx_waf#97]
In NGINX 1.23.0 some changes were made to the headers structure. Failing to compile the module with:

```
In file included from src/event/ngx_event.h:526,
                 from src/http/ngx_http_upstream.h:14,
                 from src/http/ngx_http.h:34,
                 from ngx_waf-6.1.8/inc/ngx_http_waf_module_type.h:11,
                 from ngx_waf-6.1.8/inc/ngx_http_waf_module_config.h:15,
                 from ngx_waf-6.1.8/src/ngx_http_waf_module_config.c:1:
src/event/ngx_event_udp.h:38:27: error: field 'pkt6' has incomplete type
     struct in6_pktinfo    pkt6;
                           ^~~~
```

**Comment by hibobmaster** [comment]
You can try current branch: https://github.com/ADD-SP/ngx_waf/pull/92
https://trac.nginx.org/nginx/ticket/2312

**Comment by dvershinin** [comment]
I made a pull request #99 to reorder includes in LTS, but there's another issue with NGINX 1.23.0 because there was renaming of `cookies` to `cookie` and it became a linked list in the latest NGINX.  Here's how it fails:

```
ngx_waf/src/ngx_http_waf_module_check.c: In function ‘ngx_http_waf_handler_check_black_cookie’:
ngx_waf/src/ngx_http_waf_module_check.c:613:30: error: ‘ngx_http_headers_in_t’ {aka ‘struct <anonymous>’} has no member named ‘cookies’; did you mean ‘cookie’?
     } else if (r->headers_in.cookies.nelts != 0) {
                              ^~~~~~~
                              cookie
ngx_waf/src/ngx_http_waf_module_check.c:617:52: error: ‘ngx_http_headers_in_t’ {aka ‘struct <anonymous>’} has no member named ‘cookies’; did you mean ‘cookie’?
         ngx_table_elt_t** ppcookie = r->headers_in.cookies.elts;
                                                    ^~~~~~~
                                                    cookie
ngx_waf/src/ngx_http_waf_module_check.c:619:39: error: ‘ngx_http_headers_in_t’ {aka ‘struct <anonymous>’} has no member named ‘cookies’; did you mean ‘cookie’?
         for (i = 0; i < r->headers_in.cookies.nelts; i++, ppcookie++) {
                                       ^~~~~~~
                                       cookie
```

**Comment by hibobmaster** [comment]
I got it work following the nginx changeset instructions.
https://trac.nginx.org/nginx/changeset/ef6a3a99a81acbafaf1e3537592a0e80e8f5e081/nginx
I am a newbie to c,  i don't know if there is  something wrong.
https://github.com/hibobmaster/ngx_waf/commit/1ea191fb20b0754248f2f0c2e2ff6952b5a7d2a7

**Comment by ADD-SP** [comment]
in progress

**Comment by hibobmaster** [comment]
@dvershinin I can confirm the maintainer has fixed the issue, you can try this hotfix branch
https://github.com/ADD-SP/ngx_waf/tree/hotfix/current

**Comment by dvershinin** [comment]
@hibobmaster if it's fixed, I need it to be tagged as a new LTS version, e.g. 6.1.9, for packaging purposes of mine...
(can't package off a branch commit, need a tag/release0.

**Comment by ADD-SP** [comment]
Fixed
